project:
  type: website

website:
  title: "[ <b>Business Analytics</b> & <b>Data Science</b> ]"
  # description: "Analytics & Data Science for Businesses"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/antobzzll
      - icon: linkedin
        href: https://www.linkedin.com/in/antonio-buzzelli/
format:
  html:
    theme: cosmo
    css: styles.css
    # theme:
    #   light: lumen
    #   dark: darkly
