project:
  type: website

website:
  title: "<b>Antonio Buzzelli</b> <br> Business Analytics & Data Science"
  description: "Business Analytics & Data Science"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/antobzzll
      - icon: linkedin
        href: https://www.linkedin.com/in/antonio-buzzelli/
format:
  html:
    theme: cosmo
    css: styles.css
    # theme:
    #   light: lumen
    #   dark: darkly

